### PR TITLE
feature/vdx-217

### PR DESCRIPTION
**Pull request by sksadjad**
added configs for energy shr plus some changes in the structure of the config
_still needs some changes related to the literal string values that mentioned in the ticket_

### CODE REVIEW

**Review by nklomp — COMMENTED** [review]
What's up with the manual auth? What does it do, why is it needed and how does it relate to the ticket.

Also I am seeing changes that point to your IP

**Comment by sksadjad** [comment]
> What's up with the manual auth? What does it do, why is it needed and how does it relate to the ticket.
> 
> Also I am seeing changes that point to your IP

removed those references, it was an experimental thing, and shouldn't be committed in the first place. regarding usages of `isManualIdentification` is for determining if the user is here via the manual flow vs wallet flow

**Comment by nklomp** [comment]
Yes, but why is that needed and what is the relationship to the ticket at hand?

**Comment by sksadjad** [comment]
@nklomp the ux design for this ecosystem has different images/texts depending on your flow. this is addressing these differences

**Review by nklomp — APPROVED** [review]

**Pull request merged**
